#!/usr/bin/env python3
# coding: utf-8

keywords = { "BETWEEN":"INTERCALERENTRE",
"IN":"DEDANS",
"SELECT":"SELECTIONNE",
"NOT":"PAS",
"ORDER BY":"ORDONNERPAR",
"GROUP BY":"REGROUPERPAR",
"HAVING":"AYANT",
"OR":"OUBIEN",
"AND":"AINSIQUE",
"LIKE":"SEMBLABLEA",
"INTO":"ALINTERIEUR",
"DISTINCT":"SANSDUPLICATIONS",
"SET":"DEFINIT",
"CHECK":"VERIFIEQUE",
"ROLLBACK":"RETOURENARRIERE",
"COMMIT":"COMMETTRE",
"FROM":"APARTIRDE",
"WHERE":"OÙ",
"DROP":"LACHE",
"ALTER":"MODIFIE",
"INSERT":"INSERER",
"UPDATE":"METAJOUR",
"DELETE":"SUPPRIME",
"VOID":"VIDE",
"NULL":"NÉANT",
"VALUES":"VALEURS",
"AVG":"MOYENNE",
"COUNT":"DENOMBRE",
"CONCAT":"COLLERDEUXADEUX",
"TRUNCATE":"TRONQUE",
"SLEEP":"DORMIR",
"UNION":"MISEENCONCUBINAGE",
"SAVEPOINT":"POINTDESAUVEGARDE",
"IS":"EST",
"ALL":"LINTEGRALITE",
"NUMBER":"NOMBRE",
"CHAR":"CARACTERE",
"VARCHAR2":"CARACTEREVARIABLEVERSIONDEUX",
"CROSS JOIN":"JOINTURECROISEE",
"INNER JOIN":"JOINTUREDUDEDANS",
"NATURAL JOIN":"JOINTURENATURELLE",
"=":"VAUT",
">=":"SUPERIEUROUVAUT",
"<=":"INFERIEUROUVAUT",
"<>":"NEVAUTPAS",
"#":"CROISILLON" }


def toFrench(query: str):
    for key in keywords:
        if key in query:
            query = query.replace(key,keywords[key])

    return query

def toSQL(query: str):
    pass

print(toFrench(input("Requête ?\n")))
